backend:
  name: git-gateway

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Сайт"
    files:
      - file: "content/site.json"
        label: "Контент"
        name: "content"
        fields:
          - { label: "Имя", name: "name", widget: "string" }
          - { label: "О себе", name: "about", widget: "text" }
          - { label: "Фото автора", name: "author", widget: "image" }
          - { label: "Книга", name: "book", widget: "image" }
